### ISSUE TITLE
No async public api 

### ISSUE THREAD

**Issue by dmytrohridin** [splitio/.net-core-client#131]
Hi guys,
Currently, we trying to integrate split.io product into our system with .NET Core backend.
And we a quite confused because we do not see any async public API.
Are there some reasons for it?
Thank you :)

**Comment by chillaq** [comment]
Hi Dmytro, that is correct, the SDK does connect to Redis to fetch information and write impression records, and all the network connecting calls are declared async including HTTP and Redis, we actually implemented this for redis connection in version 6.0.1, checkout the fixes history: https://github.com/splitio/.net-core-client/blob/7a62177d6ffffbaa79a762a24a8a75f2118c147a/CHANGES.txt

Thanks
Bilal

**Comment by dmytrohridin** [comment]
Got it, thank you
