### ISSUE TITLE
Cache invalidation

### ISSUE THREAD

**Issue by dmytrohridin** [splitio/.net-core-client#132]
Hi all,
Does the library support some cache invalidation? As I see it's housing memory cache by default and Redis if needed. 
Problem
For example this call returning "on" value
``` var treatment = splitClient.GetTreatment("key", "swaggerEnabled");```

But when after that I change the value in split.io app to "off" and repeat
``` var treatment = splitClient.GetTreatment("Lionbridge-CorePortal", "swaggerEnabled");```
I receive old value instead.
Maybe for each request, I should recreate ```ISplitClient```?
Thank you

**Comment by chillaq** [comment]
Hi Dmytro,

The SDK has a thread that does the synching between split cloud and the cache, the thread activation frequency is controlled by config parameter "FeaturesRefreshRate", by default it is set to 5 seconds for latest .NET SDK version, I think it used be 60 seconds in previous versions, so you do need to wait at least 5 seconds for the cache to be updated.
You can also set this parameter manually, I would set it to 5 seconds and try to repro.
If setting the parameter to 5 still does not sync the cache in that time frame, enable debug logging  to troubleshoot the issue further, checkout this link for more info: https://help.split.io/hc/en-us/articles/360020240172--NET-SDK#logging

Thanks
Bilal

**Comment by dmytrohridin** [comment]
Hi,
thank you
I found it

will close issue
