### ISSUE TITLE
Add support for Guid

### ISSUE THREAD

**Issue by bobted** [splitio/.net-core-client#174]
The `BaseMatcher` class does not support `Guid` for the value type in the base implementation of `Match()`. 

Could this be added as a simple pass through to the `string` type evaluation by calling `Guid.ToString()`?

**Comment by chillaq** [comment]
Hi, Adding a new matcher to one SDK means it will be added to the Split UI and all SDKs need to support it. I will submit a feature request on your behalf.

Thanks
Bilal

**Comment by bobted** [comment]
We are sending `Guid` types as attribute values, but couldn't figure out why we always got the default treatment back. After finding that the `BaseMatcher` does not support the `Guid` type, we updated our code to convert the `Guid` to a string when we create the attribute dictionary.

The issue we see with this approach is that the string evaluation is case sensitive - which has bit us before. If we are to have a targeting rule that uses an attribute value, we need to be extra careful with the casing that is entered for the `Guid` values.

If `Guid` types can't be supported, could there be an option to allow case insensitive string comparisons in the targeting rules?

**Comment by chillaq** [comment]
Hi, either way, this is a feature that needs to be added to the UI and all the SDKs, so it will take time to implement, even if it is case insensitive matcher.

I guess for the time being, your code needs to accommodate the feature.
