### ISSUE TITLE
SDK is not signed

### ISSUE THREAD

**Issue by ashwinp88** [splitio/.net-core-client#182]
We get an exception when attempting to load the assembly via a shared assembly. 

CSC : warning CS8002: Referenced assembly 'Splitio, Version=6.2.1.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.

**Comment by sanzmauro** [comment]
Hi @ashwinp88 we are working on that. 

We'll keep you posted here once we have the patch.

Regards,
Mauro

**Comment by sanzmauro** [comment]
@ashwinp88 I will close this issue since we fixed it in `6.2.3`

Regards,
Mauro
